project:
  type: website

website:
  title: "Melanie Berry, PsyD"
  navbar:
    background: primary
    foreground: secondary
    right:
      - text: "{{< fa brands linkedin >}}"
        href: "https://www.linkedin.com/in/melanie-berry-058472174/"
      - text: "{{< fa regular paper-plane >}}"
        href: "mailto:info@melanieberry.com"
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - speaking.qmd
      - contact.qmd
  page-footer: 
    background: none
    left: |
          <!-- 100% privacy-first analytics -->
          <script async src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
  
format:
  html:
    theme: yeti
    css: styles.css
    toc: false
    include-in-header: 
      text: |
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Figtree:ital,wght@0,300..900;1,300..900&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Literata:ital,opsz,wght@0,7..72,200..900;1,7..72,200..900&family=Source+Sans+3:ital,wght@0,200..900;1,200..900&display=swap" rel="stylesheet">
    include-after-body:
      text: |
            <script>
              document.addEventListener("DOMContentLoaded", function () {
                document.querySelectorAll('a[href^="http"]').forEach(function(link) {
                  if (!link.href.includes(window.location.hostname)) {
                    link.setAttribute('target', '_blank');
                    link.setAttribute('rel', 'noopener');
                  }
                });
              });
            </script>